version: 2
jobs:
  test:
    docker:
      - image: rust:latest
    working_directory: /usr/src/crate
    steps:
      - checkout
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test
          command: cargo test --verbose
          environment:
            RUSTFLAGS: "-C link-dead-code"
      - persist_to_workspace:
          root: target
          paths:
            - debug/panic_control-*
            - debug/test_*-*
  test_release:
    docker:
      - image: rust:latest
    working_directory: /usr/src/crate
    steps:
      - checkout
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test in release profile
          command: cargo test --verbose --release
  test_nightly:
    docker:
      - image: rustlang/rust:nightly
    working_directory: /usr/src/crate
    steps:
      - checkout
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo test --verbose
  coverage:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Rerun the tests collecting coverage
          command: |
            docker run --rm --security-opt seccomp=unconfined \
              -v "$PWD":/usr/src/crate --workdir /usr/src/crate \
              --entrypoint /bin/bash -i ragnaroek/kcov:v33 <<'EOF'
                for file in ./target/debug/*; do
                  if test -x $file; then
                    kcov --verify --exclude-pattern=tests target/coverage \
                      $file -q
                  fi
                done
            EOF
      - store_artifacts:
          path: target/coverage
          destination: coverage
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test_all_and_coverage:
    jobs:
      - test
      - test_release
      - test_nightly
      - coverage:
          requires:
            - test
